version: "3.3"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Aa123456
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 5s
      retries: 3
    networks:
      - mynet
    
  wordpress:
    depends_on:
      - db    
    build: .
    volumes:
      - ./wp:/var/www/html/wp
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    healthcheck:
      test: ["CMD", "curl", "-f", "-v", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mynet

networks:
  mynet:
volumes:
  wp: {}      
  db_data: {}
